2023-06-14 16:34:26,344 INFO    MainThread:5268 [wandb_setup.py:_flush():68] Configure stats pid to 5268
2023-06-14 16:34:26,345 INFO    MainThread:5268 [wandb_setup.py:_flush():68] Loading settings from C:\Users\DELL\.config\wandb\settings
2023-06-14 16:34:26,345 INFO    MainThread:5268 [wandb_setup.py:_flush():68] Loading settings from d:\Study\20222\ML &DM\Project\20222_DMML_Project\wandb\settings
2023-06-14 16:34:26,345 INFO    MainThread:5268 [wandb_setup.py:_flush():68] Loading settings from environment variables: {'_require_service': 'True'}
2023-06-14 16:34:26,346 INFO    MainThread:5268 [wandb_setup.py:_flush():68] Inferring run settings from compute environment: {'program': '<python with no main file>'}
2023-06-14 16:34:26,346 INFO    MainThread:5268 [wandb_setup.py:_flush():68] Applying login settings: {'api_key': '***REDACTED***'}
2023-06-14 16:34:26,347 INFO    MainThread:5268 [wandb_init.py:_log_setup():476] Logging user logs to d:\Study\20222\ML &DM\Project\20222_DMML_Project\wandb\run-20230614_163426-2oexogxa\logs\debug.log
2023-06-14 16:34:26,347 INFO    MainThread:5268 [wandb_init.py:_log_setup():477] Logging internal logs to d:\Study\20222\ML &DM\Project\20222_DMML_Project\wandb\run-20230614_163426-2oexogxa\logs\debug-internal.log
2023-06-14 16:34:26,347 INFO    MainThread:5268 [wandb_init.py:init():516] calling init triggers
2023-06-14 16:34:26,348 INFO    MainThread:5268 [wandb_init.py:init():519] wandb.init called with sweep_config: {}
config: {}
2023-06-14 16:34:26,348 INFO    MainThread:5268 [wandb_init.py:init():535] re-initializing run, found existing run on stack: 1nef2w0d
2023-06-14 16:34:26,353 INFO    MainThread:5268 [wandb_run.py:_finish():1746] finishing run thanh-bv/News Classification/1nef2w0d
2023-06-14 16:34:26,355 ERROR   MainThread:5268 [jupyter.py:save_history():440] Run pip install nbformat to save notebook history
2023-06-14 16:34:26,356 INFO    MainThread:5268 [jupyter.py:save_ipynb():378] not saving jupyter notebook
2023-06-14 16:34:26,356 INFO    MainThread:5268 [wandb_init.py:_jupyter_teardown():408] cleaning up jupyter logic
2023-06-14 16:34:26,356 INFO    MainThread:5268 [wandb_run.py:_atexit_cleanup():1949] got exitcode: 0
2023-06-14 16:34:26,357 INFO    MainThread:5268 [wandb_run.py:_restore():1932] restore
2023-06-14 16:34:26,358 INFO    MainThread:5268 [wandb_run.py:_restore():1938] restore done
2023-06-14 16:37:03,082 WARNING MsgRouterThr:5268 [router.py:message_loop():77] message_loop has been closed
2023-06-14 16:37:03,984 INFO    MainThread:5268 [wandb_run.py:_restore():1932] restore
2023-06-14 16:37:03,984 INFO    MainThread:5268 [wandb_run.py:_restore():1938] restore done
2023-06-14 16:37:04,075 ERROR   MainThread:5268 [wandb_init.py:init():1105] error
Traceback (most recent call last):
  File "C:\Users\DELL\AppData\Roaming\Python\Python310\site-packages\wandb\sdk\wandb_run.py", line 1958, in _atexit_cleanup
    self._on_finish()
  File "C:\Users\DELL\AppData\Roaming\Python\Python310\site-packages\wandb\sdk\wandb_run.py", line 2266, in _on_finish
    _ = exit_handle.wait(timeout=-1, on_progress=self._on_progress_exit)
  File "C:\Users\DELL\AppData\Roaming\Python\Python310\site-packages\wandb\sdk\lib\mailbox.py", line 273, in wait
    on_probe(probe_handle)
  File "C:\Users\DELL\AppData\Roaming\Python\Python310\site-packages\wandb\sdk\wandb_run.py", line 2228, in _on_probe_exit
    result = handle.wait(timeout=0)
  File "C:\Users\DELL\AppData\Roaming\Python\Python310\site-packages\wandb\sdk\lib\mailbox.py", line 259, in wait
    raise MailboxError("transport failed")
wandb.errors.MailboxError: transport failed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\DELL\AppData\Roaming\Python\Python310\site-packages\wandb\sdk\wandb_init.py", line 1078, in init
    run = wi.init()
  File "C:\Users\DELL\AppData\Roaming\Python\Python310\site-packages\wandb\sdk\wandb_init.py", line 548, in init
    self._wl._global_run_stack[-1].finish()
  File "C:\Users\DELL\AppData\Roaming\Python\Python310\site-packages\wandb\sdk\wandb_run.py", line 292, in wrapper
    return func(self, *args, **kwargs)
  File "C:\Users\DELL\AppData\Roaming\Python\Python310\site-packages\wandb\sdk\wandb_run.py", line 255, in wrapper
    return func(self, *args, **kwargs)
  File "C:\Users\DELL\AppData\Roaming\Python\Python310\site-packages\wandb\sdk\wandb_run.py", line 1739, in finish
    return self._finish(exit_code, quiet)
  File "C:\Users\DELL\AppData\Roaming\Python\Python310\site-packages\wandb\sdk\wandb_run.py", line 1752, in _finish
    self._atexit_cleanup(exit_code=exit_code)
  File "C:\Users\DELL\AppData\Roaming\Python\Python310\site-packages\wandb\sdk\wandb_run.py", line 1969, in _atexit_cleanup
    self._backend.cleanup()
  File "C:\Users\DELL\AppData\Roaming\Python\Python310\site-packages\wandb\sdk\backend\backend.py", line 252, in cleanup
    self.interface.join()
  File "C:\Users\DELL\AppData\Roaming\Python\Python310\site-packages\wandb\sdk\interface\interface_shared.py", line 573, in join
    super().join()
  File "C:\Users\DELL\AppData\Roaming\Python\Python310\site-packages\wandb\sdk\interface\interface.py", line 712, in join
    _ = self._communicate_shutdown()
  File "C:\Users\DELL\AppData\Roaming\Python\Python310\site-packages\wandb\sdk\interface\interface_shared.py", line 516, in _communicate_shutdown
    _ = self._communicate(record)
  File "C:\Users\DELL\AppData\Roaming\Python\Python310\site-packages\wandb\sdk\interface\interface_shared.py", line 255, in _communicate
    return self._communicate_async(rec, local=local).get(timeout=timeout)
  File "C:\Users\DELL\AppData\Roaming\Python\Python310\site-packages\wandb\sdk\interface\interface_sock.py", line 58, in _communicate_async
    future = self._router.send_and_receive(rec, local=local)
  File "C:\Users\DELL\AppData\Roaming\Python\Python310\site-packages\wandb\sdk\interface\router.py", line 94, in send_and_receive
    self._send_message(rec)
  File "C:\Users\DELL\AppData\Roaming\Python\Python310\site-packages\wandb\sdk\interface\router_sock.py", line 36, in _send_message
    self._sock_client.send_record_communicate(record)
  File "C:\Users\DELL\AppData\Roaming\Python\Python310\site-packages\wandb\sdk\lib\sock_client.py", line 216, in send_record_communicate
    self.send_server_request(server_req)
  File "C:\Users\DELL\AppData\Roaming\Python\Python310\site-packages\wandb\sdk\lib\sock_client.py", line 155, in send_server_request
    self._send_message(msg)
  File "C:\Users\DELL\AppData\Roaming\Python\Python310\site-packages\wandb\sdk\lib\sock_client.py", line 152, in _send_message
    self._sendall_with_error_handle(header + data)
  File "C:\Users\DELL\AppData\Roaming\Python\Python310\site-packages\wandb\sdk\lib\sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host
